// Code generated by protoc-gen-go.
// source: allergyIntolerance.proto
// DO NOT EDIT!

/*
Package buffer is a generated protocol buffer package.

It is generated from these files:
	allergyIntolerance.proto
	bundle.proto
	careplan.proto
	common.proto
	condition.proto
	diagnostic-report.proto
	encounter.proto
	fhirServer.proto
	goal.proto
	immunization.proto
	medication_request.proto
	observation.proto
	organization.proto
	patient.proto
	practitioner.proto
	procedure.proto

It has these top-level messages:
	Allergy
	Recorder
	Reaction
	Manifestation
	ExposureRoute
	Substance
	Reporter
	Bundle
	Entry
	OneOfResource
	Careplan
	CareTeam
	Activity
	Detail
	DailyAmount
	ProductReference
	CContained
	CParticipant
	Member
	CGoal
	Meta
	Qualification
	Subject
	Stage
	Type
	Patient
	EncounterRef
	Requester
	Performer
	Context
	Category
	Issuer
	Code
	PractitionerRole
	HealthcareService
	Period
	Role
	Location
	Organization
	Name
	Identifier
	Assigner
	Contact
	Address
	Relationship
	Extension
	Telecom
	Communication
	Language
	Coding
	Text
	ManagingOrganization
	Summary
	Asserter
	BodySite
	Severity
	Evidence
	Link
	Reason
	BasedOn
	Note
	Contained
	Actor
	Priority
	Addresses
	ConditionData
	Diagnosticreport
	Result
	PresentedForm
	DiagnosticPerformer
	Encounter
	PartOf
	EpisodeOfCare
	Appointment
	ServiceProvider
	Diagnosis
	Condition
	Class
	IncomingReferral
	Hospitalization
	Destination
	ReAdmission
	DietPreference
	SpecialArrangement
	SpecialCourtesy
	AdmitSource
	Origin
	Participant
	Individual
	StatusHistory
	Account
	ID
	QueryString
	FHIRUpdateResource
	Goal
	Target
	Measure
	DetailRange
	Low
	High
	ExpressedBy
	Description
	OutcomeReference
	Immunization
	ImmuEncounter
	VaccineCode
	MedicationRequest
	DosageInstruction
	Method
	Timing
	Repeat
	BoundsPeriod
	DoseQuantity
	Route
	MRequester
	Agent
	OnBehalfOf
	MedicationReference
	Substitution
	DispenseRequest
	Quantity
	ExpectedSupplyDuration
	ValidityPeriod
	GroupIdentifier
	Definition
	Observation
	OEncounter
	Component
	ValueQuantity
	OrganizationData
	Endpoint
	PatientData
	MaritalStatus
	PractitionerData
	Photo
	Procedure
	Outcome
	ReasonCode
	Report
	PPerformer
	FollowUp
	PerformedPeriod
*/
package buffer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Allergy struct {
	Status         string        `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Category       string        `protobuf:"bytes,2,opt,name=category" json:"category,omitempty"`
	Code           *Code         `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
	Patient        *Patient      `protobuf:"bytes,4,opt,name=patient" json:"patient,omitempty"`
	Criticality    string        `protobuf:"bytes,5,opt,name=criticality" json:"criticality,omitempty"`
	Reporter       *Reporter     `protobuf:"bytes,6,opt,name=reporter" json:"reporter,omitempty"`
	ResourceType   string        `protobuf:"bytes,7,opt,name=resourceType" json:"resourceType,omitempty"`
	Text           *Text         `protobuf:"bytes,8,opt,name=text" json:"text,omitempty"`
	Reaction       []*Reaction   `protobuf:"bytes,9,rep,name=reaction" json:"reaction,omitempty"`
	LastOccurrence string        `protobuf:"bytes,10,opt,name=lastOccurrence" json:"lastOccurrence,omitempty"`
	Onset          string        `protobuf:"bytes,11,opt,name=onset" json:"onset,omitempty"`
	Note           []*Note       `protobuf:"bytes,12,rep,name=note" json:"note,omitempty"`
	AttestedDate   string        `protobuf:"bytes,13,opt,name=attestedDate" json:"attestedDate,omitempty"`
	Recorder       *Recorder     `protobuf:"bytes,14,opt,name=recorder" json:"recorder,omitempty"`
	Identifier     []*Identifier `protobuf:"bytes,15,rep,name=identifier" json:"identifier,omitempty"`
	Type           string        `protobuf:"bytes,16,opt,name=type" json:"type,omitempty"`
	Id             string        `protobuf:"bytes,17,opt,name=id" json:"id,omitempty"`
	Meta           *Meta         `protobuf:"bytes,18,opt,name=meta" json:"meta,omitempty"`
}

func (m *Allergy) Reset()                    { *m = Allergy{} }
func (m *Allergy) String() string            { return proto.CompactTextString(m) }
func (*Allergy) ProtoMessage()               {}
func (*Allergy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Allergy) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Allergy) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Allergy) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *Allergy) GetPatient() *Patient {
	if m != nil {
		return m.Patient
	}
	return nil
}

func (m *Allergy) GetCriticality() string {
	if m != nil {
		return m.Criticality
	}
	return ""
}

func (m *Allergy) GetReporter() *Reporter {
	if m != nil {
		return m.Reporter
	}
	return nil
}

func (m *Allergy) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *Allergy) GetText() *Text {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *Allergy) GetReaction() []*Reaction {
	if m != nil {
		return m.Reaction
	}
	return nil
}

func (m *Allergy) GetLastOccurrence() string {
	if m != nil {
		return m.LastOccurrence
	}
	return ""
}

func (m *Allergy) GetOnset() string {
	if m != nil {
		return m.Onset
	}
	return ""
}

func (m *Allergy) GetNote() []*Note {
	if m != nil {
		return m.Note
	}
	return nil
}

func (m *Allergy) GetAttestedDate() string {
	if m != nil {
		return m.AttestedDate
	}
	return ""
}

func (m *Allergy) GetRecorder() *Recorder {
	if m != nil {
		return m.Recorder
	}
	return nil
}

func (m *Allergy) GetIdentifier() []*Identifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *Allergy) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Allergy) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Allergy) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Recorder struct {
	Reference string `protobuf:"bytes,1,opt,name=reference" json:"reference,omitempty"`
}

func (m *Recorder) Reset()                    { *m = Recorder{} }
func (m *Recorder) String() string            { return proto.CompactTextString(m) }
func (*Recorder) ProtoMessage()               {}
func (*Recorder) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Recorder) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

type Reaction struct {
	Substance     *Substance       `protobuf:"bytes,1,opt,name=substance" json:"substance,omitempty"`
	Severity      string           `protobuf:"bytes,2,opt,name=severity" json:"severity,omitempty"`
	Certainty     string           `protobuf:"bytes,3,opt,name=certainty" json:"certainty,omitempty"`
	ExposureRoute *ExposureRoute   `protobuf:"bytes,4,opt,name=exposureRoute" json:"exposureRoute,omitempty"`
	Onset         string           `protobuf:"bytes,5,opt,name=onset" json:"onset,omitempty"`
	Manifestation []*Manifestation `protobuf:"bytes,6,rep,name=manifestation" json:"manifestation,omitempty"`
	Description   string           `protobuf:"bytes,7,opt,name=description" json:"description,omitempty"`
}

func (m *Reaction) Reset()                    { *m = Reaction{} }
func (m *Reaction) String() string            { return proto.CompactTextString(m) }
func (*Reaction) ProtoMessage()               {}
func (*Reaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Reaction) GetSubstance() *Substance {
	if m != nil {
		return m.Substance
	}
	return nil
}

func (m *Reaction) GetSeverity() string {
	if m != nil {
		return m.Severity
	}
	return ""
}

func (m *Reaction) GetCertainty() string {
	if m != nil {
		return m.Certainty
	}
	return ""
}

func (m *Reaction) GetExposureRoute() *ExposureRoute {
	if m != nil {
		return m.ExposureRoute
	}
	return nil
}

func (m *Reaction) GetOnset() string {
	if m != nil {
		return m.Onset
	}
	return ""
}

func (m *Reaction) GetManifestation() []*Manifestation {
	if m != nil {
		return m.Manifestation
	}
	return nil
}

func (m *Reaction) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Manifestation struct {
	Coding []*Coding `protobuf:"bytes,1,rep,name=coding" json:"coding,omitempty"`
}

func (m *Manifestation) Reset()                    { *m = Manifestation{} }
func (m *Manifestation) String() string            { return proto.CompactTextString(m) }
func (*Manifestation) ProtoMessage()               {}
func (*Manifestation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Manifestation) GetCoding() []*Coding {
	if m != nil {
		return m.Coding
	}
	return nil
}

type ExposureRoute struct {
	Coding []*Coding `protobuf:"bytes,1,rep,name=coding" json:"coding,omitempty"`
}

func (m *ExposureRoute) Reset()                    { *m = ExposureRoute{} }
func (m *ExposureRoute) String() string            { return proto.CompactTextString(m) }
func (*ExposureRoute) ProtoMessage()               {}
func (*ExposureRoute) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ExposureRoute) GetCoding() []*Coding {
	if m != nil {
		return m.Coding
	}
	return nil
}

type Substance struct {
	Coding []*Coding `protobuf:"bytes,1,rep,name=coding" json:"coding,omitempty"`
}

func (m *Substance) Reset()                    { *m = Substance{} }
func (m *Substance) String() string            { return proto.CompactTextString(m) }
func (*Substance) ProtoMessage()               {}
func (*Substance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Substance) GetCoding() []*Coding {
	if m != nil {
		return m.Coding
	}
	return nil
}

type Reporter struct {
	Reference string `protobuf:"bytes,1,opt,name=reference" json:"reference,omitempty"`
}

func (m *Reporter) Reset()                    { *m = Reporter{} }
func (m *Reporter) String() string            { return proto.CompactTextString(m) }
func (*Reporter) ProtoMessage()               {}
func (*Reporter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Reporter) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func init() {
	proto.RegisterType((*Allergy)(nil), "buffer.Allergy")
	proto.RegisterType((*Recorder)(nil), "buffer.Recorder")
	proto.RegisterType((*Reaction)(nil), "buffer.Reaction")
	proto.RegisterType((*Manifestation)(nil), "buffer.Manifestation")
	proto.RegisterType((*ExposureRoute)(nil), "buffer.ExposureRoute")
	proto.RegisterType((*Substance)(nil), "buffer.Substance")
	proto.RegisterType((*Reporter)(nil), "buffer.Reporter")
}

func init() { proto.RegisterFile("allergyIntolerance.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x3f, 0x6f, 0xdb, 0x3e,
	0x10, 0x85, 0x1d, 0x47, 0xb6, 0xce, 0x7f, 0x92, 0x10, 0xbf, 0x5f, 0x41, 0x04, 0x1d, 0x0c, 0x0f,
	0x81, 0x0b, 0x14, 0x2e, 0xe0, 0x0c, 0x1d, 0x32, 0x15, 0x6d, 0x87, 0x0c, 0x69, 0x0b, 0x36, 0x5f,
	0x80, 0xa6, 0xce, 0x06, 0x01, 0x9b, 0x14, 0xa8, 0x53, 0x61, 0x7f, 0xa2, 0x7e, 0xc7, 0x4e, 0x05,
	0x49, 0x49, 0x96, 0x32, 0x14, 0xd9, 0xc4, 0xf7, 0xde, 0xdd, 0xe3, 0x1d, 0xef, 0x04, 0x5c, 0xee,
	0xf7, 0xe8, 0x76, 0xa7, 0x47, 0x43, 0x76, 0x8f, 0x4e, 0x1a, 0x85, 0xab, 0xdc, 0x59, 0xb2, 0x2c,
	0xd9, 0x94, 0xdb, 0x2d, 0xba, 0xdb, 0x89, 0xb2, 0x87, 0x83, 0x35, 0x11, 0x5d, 0xfc, 0x19, 0xc0,
	0xf0, 0x53, 0x0c, 0x61, 0x6f, 0x20, 0x29, 0x48, 0x52, 0x59, 0xf0, 0xde, 0xbc, 0xb7, 0x4c, 0x45,
	0x75, 0x62, 0xb7, 0x30, 0x52, 0x92, 0x70, 0x67, 0xdd, 0x89, 0xf7, 0x03, 0xd3, 0x9c, 0xd9, 0x1c,
	0x06, 0xca, 0x66, 0xc8, 0x2f, 0xe6, 0xbd, 0xe5, 0x78, 0x3d, 0x59, 0x45, 0x93, 0xd5, 0x67, 0x9b,
	0xa1, 0x08, 0x0c, 0x7b, 0x07, 0xc3, 0x5c, 0x92, 0x46, 0x43, 0x7c, 0x10, 0x44, 0x57, 0xb5, 0xe8,
	0x47, 0x84, 0x45, 0xcd, 0xb3, 0x39, 0x8c, 0x95, 0xd3, 0xa4, 0x95, 0xdc, 0x6b, 0x3a, 0xf1, 0xcb,
	0xe0, 0xd5, 0x86, 0xd8, 0x7b, 0x18, 0x39, 0xcc, 0xad, 0x23, 0x74, 0x3c, 0x09, 0xd9, 0xae, 0xeb,
	0x6c, 0xa2, 0xc2, 0x45, 0xa3, 0x60, 0x0b, 0x98, 0x38, 0x2c, 0x6c, 0xe9, 0x14, 0x3e, 0x9f, 0x72,
	0xe4, 0xc3, 0x90, 0xb0, 0x83, 0xf9, 0x02, 0x08, 0x8f, 0xc4, 0x47, 0xdd, 0x02, 0x9e, 0xf1, 0x48,
	0x22, 0x30, 0xd1, 0x53, 0x2a, 0xd2, 0xd6, 0xf0, 0x74, 0x7e, 0xd1, 0xf5, 0x8c, 0xb8, 0x68, 0x14,
	0xec, 0x0e, 0x66, 0x7b, 0x59, 0xd0, 0x77, 0xa5, 0x4a, 0xe7, 0xd0, 0x28, 0xe4, 0x10, 0x5c, 0x5f,
	0xa0, 0xec, 0x3f, 0xb8, 0xb4, 0xa6, 0x40, 0xe2, 0xe3, 0x40, 0xc7, 0x83, 0xbf, 0x8d, 0xb1, 0x84,
	0x7c, 0x12, 0x7c, 0x9a, 0xdb, 0x7c, 0xb3, 0x84, 0x22, 0x30, 0xbe, 0x26, 0x49, 0x84, 0x05, 0x61,
	0xf6, 0x45, 0x12, 0xf2, 0x69, 0xac, 0xa9, 0x8d, 0xc5, 0x1b, 0x2b, 0xeb, 0x32, 0x74, 0x7c, 0xf6,
	0xb2, 0x4b, 0x11, 0x17, 0x8d, 0x82, 0xad, 0x01, 0x74, 0x86, 0x86, 0xf4, 0x56, 0xa3, 0xe3, 0x57,
	0xc1, 0x99, 0xd5, 0xfa, 0xc7, 0x86, 0x11, 0x2d, 0x15, 0x63, 0x30, 0x20, 0xdf, 0xd1, 0xeb, 0xe0,
	0x1e, 0xbe, 0xd9, 0x0c, 0xfa, 0x3a, 0xe3, 0x37, 0x01, 0xe9, 0xeb, 0xcc, 0xd7, 0x72, 0x40, 0x92,
	0x9c, 0x75, 0x3b, 0xfb, 0x84, 0x24, 0x45, 0x60, 0x16, 0x4b, 0x18, 0xd5, 0xf7, 0x61, 0x6f, 0x21,
	0x75, 0xb8, 0xc5, 0xd8, 0xb2, 0x38, 0x7f, 0x67, 0x60, 0xf1, 0xbb, 0xef, 0xa5, 0x55, 0x8b, 0x3f,
	0x40, 0x5a, 0x94, 0x9b, 0x82, 0x64, 0x2d, 0x1d, 0xaf, 0x6f, 0xea, 0xec, 0x3f, 0x6b, 0x42, 0x9c,
	0x35, 0x7e, 0x80, 0x0b, 0xfc, 0x85, 0xce, 0x0f, 0x55, 0x35, 0xc0, 0xf5, 0xd9, 0xfb, 0x2a, 0x74,
	0x24, 0xb5, 0xa1, 0x53, 0x98, 0xe2, 0x54, 0x9c, 0x01, 0xf6, 0x00, 0x53, 0x3c, 0xe6, 0xb6, 0x28,
	0x1d, 0x0a, 0x5b, 0x12, 0x56, 0x23, 0xfc, 0x7f, 0x6d, 0xf7, 0xb5, 0x4d, 0x8a, 0xae, 0xf6, 0xfc,
	0xc4, 0x97, 0xed, 0x27, 0x7e, 0x80, 0xe9, 0x41, 0x1a, 0xbd, 0x45, 0xbf, 0x5d, 0x7e, 0xa6, 0x92,
	0xd0, 0xf1, 0x26, 0xe5, 0x53, 0x9b, 0x14, 0x5d, 0xad, 0xdf, 0x90, 0x0c, 0x0b, 0xe5, 0x74, 0x1e,
	0x42, 0xe3, 0x40, 0xb7, 0xa1, 0xc5, 0x47, 0x98, 0x76, 0x32, 0xb0, 0x3b, 0x48, 0x94, 0xcd, 0xb4,
	0xd9, 0xf1, 0x5e, 0x30, 0x9a, 0xb5, 0x76, 0x54, 0x9b, 0x9d, 0xa8, 0x58, 0x1f, 0xd8, 0xa9, 0xe6,
	0xd5, 0x81, 0xf7, 0x90, 0x36, 0x5d, 0x7f, 0x75, 0x50, 0x78, 0xfa, 0x6a, 0x4d, 0xff, 0xf9, 0xf4,
	0x9b, 0x24, 0xfc, 0xa8, 0xee, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x45, 0x4b, 0x22, 0xda,
	0x04, 0x00, 0x00,
}
