// Code generated by protoc-gen-go.
// source: bundle.proto
// DO NOT EDIT!

package buffer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Bundle struct {
	ResourceType string   `protobuf:"bytes,1,opt,name=resourceType" json:"resourceType,omitempty"`
	Link         []*Link  `protobuf:"bytes,2,rep,name=link" json:"link,omitempty"`
	Total        int64    `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
	Type         string   `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	Entry        []*Entry `protobuf:"bytes,5,rep,name=entry" json:"entry,omitempty"`
}

func (m *Bundle) Reset()                    { *m = Bundle{} }
func (m *Bundle) String() string            { return proto.CompactTextString(m) }
func (*Bundle) ProtoMessage()               {}
func (*Bundle) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Bundle) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *Bundle) GetLink() []*Link {
	if m != nil {
		return m.Link
	}
	return nil
}

func (m *Bundle) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Bundle) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Bundle) GetEntry() []*Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type Entry struct {
	FullUrl  string `protobuf:"bytes,1,opt,name=fullUrl" json:"fullUrl,omitempty"`
	Resource string `protobuf:"bytes,2,opt,name=resource" json:"resource,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Entry) GetFullUrl() string {
	if m != nil {
		return m.FullUrl
	}
	return ""
}

func (m *Entry) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

type OneOfResource struct {
	// Types that are valid to be assigned to Resource:
	//	*OneOfResource_Patient
	//	*OneOfResource_Provider
	//	*OneOfResource_Observation
	//	*OneOfResource_MedicationRequest
	Resource isOneOfResource_Resource `protobuf_oneof:"resource"`
}

func (m *OneOfResource) Reset()                    { *m = OneOfResource{} }
func (m *OneOfResource) String() string            { return proto.CompactTextString(m) }
func (*OneOfResource) ProtoMessage()               {}
func (*OneOfResource) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type isOneOfResource_Resource interface {
	isOneOfResource_Resource()
}

type OneOfResource_Patient struct {
	Patient *PatientData `protobuf:"bytes,1,opt,name=patient,oneof"`
}
type OneOfResource_Provider struct {
	Provider *PractitionerData `protobuf:"bytes,2,opt,name=provider,oneof"`
}
type OneOfResource_Observation struct {
	Observation *Observation `protobuf:"bytes,3,opt,name=observation,oneof"`
}
type OneOfResource_MedicationRequest struct {
	MedicationRequest *MedicationRequest `protobuf:"bytes,4,opt,name=medication_request,json=medicationRequest,oneof"`
}

func (*OneOfResource_Patient) isOneOfResource_Resource()           {}
func (*OneOfResource_Provider) isOneOfResource_Resource()          {}
func (*OneOfResource_Observation) isOneOfResource_Resource()       {}
func (*OneOfResource_MedicationRequest) isOneOfResource_Resource() {}

func (m *OneOfResource) GetResource() isOneOfResource_Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *OneOfResource) GetPatient() *PatientData {
	if x, ok := m.GetResource().(*OneOfResource_Patient); ok {
		return x.Patient
	}
	return nil
}

func (m *OneOfResource) GetProvider() *PractitionerData {
	if x, ok := m.GetResource().(*OneOfResource_Provider); ok {
		return x.Provider
	}
	return nil
}

func (m *OneOfResource) GetObservation() *Observation {
	if x, ok := m.GetResource().(*OneOfResource_Observation); ok {
		return x.Observation
	}
	return nil
}

func (m *OneOfResource) GetMedicationRequest() *MedicationRequest {
	if x, ok := m.GetResource().(*OneOfResource_MedicationRequest); ok {
		return x.MedicationRequest
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*OneOfResource) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _OneOfResource_OneofMarshaler, _OneOfResource_OneofUnmarshaler, _OneOfResource_OneofSizer, []interface{}{
		(*OneOfResource_Patient)(nil),
		(*OneOfResource_Provider)(nil),
		(*OneOfResource_Observation)(nil),
		(*OneOfResource_MedicationRequest)(nil),
	}
}

func _OneOfResource_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*OneOfResource)
	// resource
	switch x := m.Resource.(type) {
	case *OneOfResource_Patient:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Patient); err != nil {
			return err
		}
	case *OneOfResource_Provider:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Provider); err != nil {
			return err
		}
	case *OneOfResource_Observation:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Observation); err != nil {
			return err
		}
	case *OneOfResource_MedicationRequest:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MedicationRequest); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("OneOfResource.Resource has unexpected type %T", x)
	}
	return nil
}

func _OneOfResource_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*OneOfResource)
	switch tag {
	case 1: // resource.patient
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PatientData)
		err := b.DecodeMessage(msg)
		m.Resource = &OneOfResource_Patient{msg}
		return true, err
	case 2: // resource.provider
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PractitionerData)
		err := b.DecodeMessage(msg)
		m.Resource = &OneOfResource_Provider{msg}
		return true, err
	case 3: // resource.observation
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Observation)
		err := b.DecodeMessage(msg)
		m.Resource = &OneOfResource_Observation{msg}
		return true, err
	case 4: // resource.medication_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MedicationRequest)
		err := b.DecodeMessage(msg)
		m.Resource = &OneOfResource_MedicationRequest{msg}
		return true, err
	default:
		return false, nil
	}
}

func _OneOfResource_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*OneOfResource)
	// resource
	switch x := m.Resource.(type) {
	case *OneOfResource_Patient:
		s := proto.Size(x.Patient)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *OneOfResource_Provider:
		s := proto.Size(x.Provider)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *OneOfResource_Observation:
		s := proto.Size(x.Observation)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *OneOfResource_MedicationRequest:
		s := proto.Size(x.MedicationRequest)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Bundle)(nil), "buffer.Bundle")
	proto.RegisterType((*Entry)(nil), "buffer.Entry")
	proto.RegisterType((*OneOfResource)(nil), "buffer.OneOfResource")
}

func init() { proto.RegisterFile("bundle.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x4f, 0xea, 0x40,
	0x10, 0xc7, 0x29, 0x50, 0xe0, 0x4d, 0xcb, 0x81, 0x79, 0xef, 0xb0, 0x8f, 0x53, 0x53, 0x2f, 0x9c,
	0x30, 0xa9, 0x89, 0x9e, 0xbc, 0x10, 0x4d, 0x88, 0xd1, 0x60, 0x36, 0x7a, 0x36, 0x6d, 0x99, 0x26,
	0x0d, 0x6d, 0xb7, 0x2e, 0x5b, 0x12, 0x3e, 0x82, 0x1f, 0xc2, 0xef, 0x6a, 0xd8, 0x76, 0x4b, 0xd5,
	0xdb, 0xce, 0x6f, 0xfe, 0xfb, 0x9f, 0xc9, 0xfc, 0xc1, 0x8d, 0xaa, 0x62, 0x9b, 0xd1, 0xb2, 0x94,
	0x42, 0x09, 0x1c, 0x45, 0x55, 0x92, 0x90, 0x9c, 0x4f, 0xcb, 0x50, 0xa5, 0x54, 0xa8, 0x1a, 0xcf,
	0xb1, 0x94, 0x61, 0xac, 0x52, 0x95, 0x8a, 0x82, 0x64, 0xc3, 0x66, 0x22, 0xda, 0x93, 0x3c, 0x84,
	0x27, 0xd8, 0x20, 0x96, 0xd3, 0x36, 0x8d, 0x35, 0x79, 0x93, 0xf4, 0x5e, 0xd1, 0xde, 0x18, 0xb8,
	0xb1, 0xc8, 0x73, 0xa3, 0xf3, 0x3f, 0x2d, 0x18, 0xad, 0xf4, 0x58, 0xf4, 0xc1, 0x95, 0xb4, 0x17,
	0x95, 0x8c, 0xe9, 0xe5, 0x58, 0x12, 0xb3, 0x3c, 0x6b, 0xf1, 0x87, 0x7f, 0x63, 0xe8, 0xc1, 0x30,
	0x4b, 0x8b, 0x1d, 0xeb, 0x7b, 0x83, 0x85, 0x13, 0xb8, 0xcb, 0x7a, 0xc7, 0xe5, 0x63, 0x5a, 0xec,
	0xb8, 0xee, 0xe0, 0x3f, 0xb0, 0x95, 0x50, 0x61, 0xc6, 0x06, 0x9e, 0xb5, 0x18, 0xf0, 0xba, 0x40,
	0x84, 0xa1, 0x3a, 0x79, 0x0e, 0xb5, 0xa7, 0x7e, 0xe3, 0x05, 0xd8, 0x54, 0x28, 0x79, 0x64, 0xb6,
	0x36, 0x9b, 0x1a, 0xb3, 0xfb, 0x13, 0xe4, 0x75, 0xcf, 0xbf, 0x05, 0x5b, 0xd7, 0xc8, 0x60, 0x9c,
	0x54, 0x59, 0xf6, 0x2a, 0xb3, 0x66, 0x31, 0x53, 0xe2, 0x1c, 0x26, 0x66, 0x47, 0xd6, 0xd7, 0xad,
	0xb6, 0xf6, 0x3f, 0xfa, 0x30, 0xdd, 0x14, 0xb4, 0x49, 0x78, 0x43, 0xf0, 0x12, 0xc6, 0xcd, 0x41,
	0xb5, 0x8f, 0x13, 0xfc, 0x35, 0x73, 0x9f, 0x6b, 0x7c, 0x17, 0xaa, 0x70, 0xdd, 0xe3, 0x46, 0x85,
	0xd7, 0x30, 0x29, 0xa5, 0x38, 0xa4, 0x5b, 0x92, 0xda, 0xde, 0x09, 0x58, 0xfb, 0xa3, 0x13, 0x45,
	0xf3, 0xad, 0xd5, 0xe2, 0x0d, 0x38, 0x9d, 0x58, 0xf4, 0x39, 0x3a, 0xc3, 0x36, 0xe7, 0xd6, 0xba,
	0xc7, 0xbb, 0x4a, 0x7c, 0x00, 0xfc, 0x1d, 0x9e, 0xbe, 0x9c, 0x13, 0xfc, 0x37, 0xff, 0x9f, 0x5a,
	0x05, 0xaf, 0x05, 0xeb, 0x1e, 0x9f, 0xe5, 0x3f, 0xe1, 0x0a, 0xce, 0xb7, 0x89, 0x46, 0x3a, 0xf1,
	0xab, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x78, 0x8d, 0x17, 0xd9, 0x67, 0x02, 0x00, 0x00,
}
