// Code generated by protoc-gen-go.
// source: careplan.proto
// DO NOT EDIT!

package buffer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Careplan struct {
	Status       string        `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Addresses    []*Addresses  `protobuf:"bytes,2,rep,name=addresses" json:"addresses,omitempty"`
	ResourceType string        `protobuf:"bytes,3,opt,name=resourceType" json:"resourceType,omitempty"`
	Text         *Text         `protobuf:"bytes,4,opt,name=text" json:"text,omitempty"`
	Goal         []*CGoal      `protobuf:"bytes,5,rep,name=goal" json:"goal,omitempty"`
	Period       *Period       `protobuf:"bytes,6,opt,name=period" json:"period,omitempty"`
	Contained    []*CContained `protobuf:"bytes,7,rep,name=contained" json:"contained,omitempty"`
	Intent       string        `protobuf:"bytes,8,opt,name=intent" json:"intent,omitempty"`
	Activity     []*Activity   `protobuf:"bytes,9,rep,name=activity" json:"activity,omitempty"`
	CareTeam     []*CareTeam   `protobuf:"bytes,10,rep,name=careTeam" json:"careTeam,omitempty"`
	Id           string        `protobuf:"bytes,11,opt,name=id" json:"id,omitempty"`
	Subject      *Subject      `protobuf:"bytes,12,opt,name=subject" json:"subject,omitempty"`
}

func (m *Careplan) Reset()                    { *m = Careplan{} }
func (m *Careplan) String() string            { return proto.CompactTextString(m) }
func (*Careplan) ProtoMessage()               {}
func (*Careplan) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Careplan) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Careplan) GetAddresses() []*Addresses {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Careplan) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *Careplan) GetText() *Text {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *Careplan) GetGoal() []*CGoal {
	if m != nil {
		return m.Goal
	}
	return nil
}

func (m *Careplan) GetPeriod() *Period {
	if m != nil {
		return m.Period
	}
	return nil
}

func (m *Careplan) GetContained() []*CContained {
	if m != nil {
		return m.Contained
	}
	return nil
}

func (m *Careplan) GetIntent() string {
	if m != nil {
		return m.Intent
	}
	return ""
}

func (m *Careplan) GetActivity() []*Activity {
	if m != nil {
		return m.Activity
	}
	return nil
}

func (m *Careplan) GetCareTeam() []*CareTeam {
	if m != nil {
		return m.CareTeam
	}
	return nil
}

func (m *Careplan) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Careplan) GetSubject() *Subject {
	if m != nil {
		return m.Subject
	}
	return nil
}

type CareTeam struct {
	Reference string `protobuf:"bytes,1,opt,name=reference" json:"reference,omitempty"`
}

func (m *CareTeam) Reset()                    { *m = CareTeam{} }
func (m *CareTeam) String() string            { return proto.CompactTextString(m) }
func (*CareTeam) ProtoMessage()               {}
func (*CareTeam) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *CareTeam) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

type Activity struct {
	Detail *Detail `protobuf:"bytes,1,opt,name=detail" json:"detail,omitempty"`
}

func (m *Activity) Reset()                    { *m = Activity{} }
func (m *Activity) String() string            { return proto.CompactTextString(m) }
func (*Activity) ProtoMessage()               {}
func (*Activity) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *Activity) GetDetail() *Detail {
	if m != nil {
		return m.Detail
	}
	return nil
}

type Detail struct {
	Category         *Category         `protobuf:"bytes,1,opt,name=category" json:"category,omitempty"`
	Status           string            `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	Code             *Code             `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
	ProductReference *ProductReference `protobuf:"bytes,4,opt,name=productReference" json:"productReference,omitempty"`
	ScheduledString  string            `protobuf:"bytes,5,opt,name=scheduledString" json:"scheduledString,omitempty"`
	Prohibited       bool              `protobuf:"varint,6,opt,name=prohibited" json:"prohibited,omitempty"`
	DailyAmount      *DailyAmount      `protobuf:"bytes,7,opt,name=dailyAmount" json:"dailyAmount,omitempty"`
}

func (m *Detail) Reset()                    { *m = Detail{} }
func (m *Detail) String() string            { return proto.CompactTextString(m) }
func (*Detail) ProtoMessage()               {}
func (*Detail) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *Detail) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *Detail) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Detail) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *Detail) GetProductReference() *ProductReference {
	if m != nil {
		return m.ProductReference
	}
	return nil
}

func (m *Detail) GetScheduledString() string {
	if m != nil {
		return m.ScheduledString
	}
	return ""
}

func (m *Detail) GetProhibited() bool {
	if m != nil {
		return m.Prohibited
	}
	return false
}

func (m *Detail) GetDailyAmount() *DailyAmount {
	if m != nil {
		return m.DailyAmount
	}
	return nil
}

type DailyAmount struct {
	Code   string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Value  int64  `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Unit   string `protobuf:"bytes,3,opt,name=unit" json:"unit,omitempty"`
	System string `protobuf:"bytes,4,opt,name=system" json:"system,omitempty"`
}

func (m *DailyAmount) Reset()                    { *m = DailyAmount{} }
func (m *DailyAmount) String() string            { return proto.CompactTextString(m) }
func (*DailyAmount) ProtoMessage()               {}
func (*DailyAmount) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *DailyAmount) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DailyAmount) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *DailyAmount) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *DailyAmount) GetSystem() string {
	if m != nil {
		return m.System
	}
	return ""
}

type ProductReference struct {
	Display   string `protobuf:"bytes,1,opt,name=display" json:"display,omitempty"`
	Reference string `protobuf:"bytes,2,opt,name=reference" json:"reference,omitempty"`
}

func (m *ProductReference) Reset()                    { *m = ProductReference{} }
func (m *ProductReference) String() string            { return proto.CompactTextString(m) }
func (*ProductReference) ProtoMessage()               {}
func (*ProductReference) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *ProductReference) GetDisplay() string {
	if m != nil {
		return m.Display
	}
	return ""
}

func (m *ProductReference) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

type CContained struct {
	ResourceType string          `protobuf:"bytes,1,opt,name=resourceType" json:"resourceType,omitempty"`
	Participant  []*CParticipant `protobuf:"bytes,2,rep,name=participant" json:"participant,omitempty"`
	Id           string          `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *CContained) Reset()                    { *m = CContained{} }
func (m *CContained) String() string            { return proto.CompactTextString(m) }
func (*CContained) ProtoMessage()               {}
func (*CContained) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *CContained) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *CContained) GetParticipant() []*CParticipant {
	if m != nil {
		return m.Participant
	}
	return nil
}

func (m *CContained) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CParticipant struct {
	Member *Member `protobuf:"bytes,1,opt,name=member" json:"member,omitempty"`
	Role   *Role   `protobuf:"bytes,2,opt,name=role" json:"role,omitempty"`
}

func (m *CParticipant) Reset()                    { *m = CParticipant{} }
func (m *CParticipant) String() string            { return proto.CompactTextString(m) }
func (*CParticipant) ProtoMessage()               {}
func (*CParticipant) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *CParticipant) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

func (m *CParticipant) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type Member struct {
	Display   string `protobuf:"bytes,1,opt,name=display" json:"display,omitempty"`
	Reference string `protobuf:"bytes,2,opt,name=reference" json:"reference,omitempty"`
}

func (m *Member) Reset()                    { *m = Member{} }
func (m *Member) String() string            { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()               {}
func (*Member) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *Member) GetDisplay() string {
	if m != nil {
		return m.Display
	}
	return ""
}

func (m *Member) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

type CGoal struct {
	Reference string `protobuf:"bytes,1,opt,name=reference" json:"reference,omitempty"`
}

func (m *CGoal) Reset()                    { *m = CGoal{} }
func (m *CGoal) String() string            { return proto.CompactTextString(m) }
func (*CGoal) ProtoMessage()               {}
func (*CGoal) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *CGoal) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func init() {
	proto.RegisterType((*Careplan)(nil), "buffer.Careplan")
	proto.RegisterType((*CareTeam)(nil), "buffer.CareTeam")
	proto.RegisterType((*Activity)(nil), "buffer.Activity")
	proto.RegisterType((*Detail)(nil), "buffer.Detail")
	proto.RegisterType((*DailyAmount)(nil), "buffer.DailyAmount")
	proto.RegisterType((*ProductReference)(nil), "buffer.ProductReference")
	proto.RegisterType((*CContained)(nil), "buffer.CContained")
	proto.RegisterType((*CParticipant)(nil), "buffer.CParticipant")
	proto.RegisterType((*Member)(nil), "buffer.Member")
	proto.RegisterType((*CGoal)(nil), "buffer.CGoal")
}

func init() { proto.RegisterFile("careplan.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5f, 0x6b, 0xdb, 0x3e,
	0x14, 0x25, 0xff, 0x9c, 0xe4, 0x26, 0xbf, 0xb6, 0x3f, 0xad, 0x0c, 0x31, 0xc6, 0xc8, 0x0c, 0x1b,
	0x19, 0x8c, 0x6e, 0x74, 0x6c, 0xcf, 0x2b, 0x29, 0x0c, 0x06, 0x83, 0xa2, 0xf6, 0x61, 0xaf, 0x8a,
	0x75, 0xdb, 0x6a, 0xd8, 0x96, 0x91, 0xe5, 0x92, 0x7c, 0xb2, 0x7d, 0x82, 0x7d, 0xaf, 0xe1, 0x2b,
	0xd9, 0x71, 0xd2, 0xb1, 0x87, 0xbd, 0x59, 0xe7, 0x1c, 0x5d, 0xeb, 0x9e, 0x7b, 0x24, 0x38, 0x4a,
	0xa4, 0xc5, 0x22, 0x95, 0xf9, 0x59, 0x61, 0x8d, 0x33, 0x2c, 0x5a, 0x57, 0xb7, 0xb7, 0x68, 0x9f,
	0xcd, 0x13, 0x93, 0x65, 0x26, 0xa0, 0xf1, 0xaf, 0x01, 0x4c, 0x56, 0x41, 0xc8, 0x9e, 0x42, 0x54,
	0x3a, 0xe9, 0xaa, 0x92, 0xf7, 0x16, 0xbd, 0xe5, 0x54, 0x84, 0x15, 0x7b, 0x07, 0x53, 0xa9, 0x94,
	0xc5, 0xb2, 0xc4, 0x92, 0xf7, 0x17, 0x83, 0xe5, 0xec, 0xfc, 0xff, 0x33, 0x5f, 0xee, 0xec, 0xa2,
	0x21, 0xc4, 0x4e, 0xc3, 0x62, 0x98, 0x5b, 0x2c, 0x4d, 0x65, 0x13, 0xbc, 0xd9, 0x16, 0xc8, 0x07,
	0x54, 0x6e, 0x0f, 0x63, 0x0b, 0x18, 0x3a, 0xdc, 0x38, 0x3e, 0x5c, 0xf4, 0x96, 0xb3, 0xf3, 0x79,
	0x53, 0xef, 0x06, 0x37, 0x4e, 0x10, 0xc3, 0x5e, 0xc2, 0xf0, 0xce, 0xc8, 0x94, 0x8f, 0xe8, 0x8f,
	0xff, 0x35, 0x8a, 0xd5, 0x17, 0x23, 0x53, 0x41, 0x14, 0x7b, 0x0d, 0x51, 0x81, 0x56, 0x1b, 0xc5,
	0x23, 0x2a, 0x73, 0xd4, 0x88, 0xae, 0x08, 0x15, 0x81, 0x65, 0xef, 0x61, 0x9a, 0x98, 0xdc, 0x49,
	0x9d, 0xa3, 0xe2, 0x63, 0xaa, 0xc7, 0xda, 0x7a, 0xab, 0x86, 0x11, 0x3b, 0x51, 0xed, 0x85, 0xce,
	0x1d, 0xe6, 0x8e, 0x4f, 0xbc, 0x17, 0x7e, 0xc5, 0xde, 0xc2, 0x44, 0x26, 0x4e, 0x3f, 0x68, 0xb7,
	0xe5, 0x53, 0x2a, 0x74, 0xd2, 0x5a, 0x11, 0x70, 0xd1, 0x2a, 0x6a, 0x75, 0x3d, 0x86, 0x1b, 0x94,
	0x19, 0x87, 0x7d, 0xf5, 0x2a, 0xe0, 0xa2, 0x55, 0xb0, 0x23, 0xe8, 0x6b, 0xc5, 0x67, 0xf4, 0xbf,
	0xbe, 0x56, 0xec, 0x0d, 0x8c, 0xcb, 0x6a, 0xfd, 0x03, 0x13, 0xc7, 0xe7, 0xd4, 0xde, 0x71, 0xb3,
	0xf9, 0xda, 0xc3, 0xa2, 0xe1, 0xe3, 0xa5, 0x1f, 0x23, 0x95, 0x79, 0x0e, 0x53, 0x8b, 0xb7, 0x68,
	0x31, 0x4f, 0x30, 0x4c, 0x72, 0x07, 0xc4, 0xe7, 0x30, 0x69, 0x0e, 0x5a, 0xdb, 0xa7, 0xd0, 0x49,
	0x9d, 0x92, 0xac, 0x63, 0xdf, 0x25, 0xa1, 0x22, 0xb0, 0xf1, 0xcf, 0x3e, 0x44, 0x1e, 0xf2, 0x1d,
	0x39, 0xbc, 0x33, 0x76, 0x1b, 0x36, 0x75, 0x3a, 0xf2, 0xb8, 0x68, 0x15, 0x9d, 0x44, 0xf5, 0xf7,
	0x12, 0xb5, 0x80, 0x61, 0x62, 0x94, 0x0f, 0x46, 0x67, 0xf8, 0x2b, 0xa3, 0x50, 0x10, 0xc3, 0x2e,
	0xe1, 0xa4, 0xb0, 0x46, 0x55, 0x89, 0x13, 0x6d, 0x2f, 0x3e, 0x2a, 0xbc, 0x9d, 0xf1, 0x01, 0x2f,
	0x1e, 0xed, 0x60, 0x4b, 0x38, 0x2e, 0x93, 0x7b, 0x54, 0x55, 0x8a, 0xea, 0xda, 0x59, 0x9d, 0xdf,
	0xf1, 0x11, 0x1d, 0xe4, 0x10, 0x66, 0x2f, 0x00, 0x0a, 0x6b, 0xee, 0xf5, 0x5a, 0x3b, 0xf4, 0x69,
	0x9a, 0x88, 0x0e, 0xc2, 0x3e, 0xc2, 0x4c, 0x49, 0x9d, 0x6e, 0x2f, 0x32, 0x53, 0xe5, 0x8e, 0x8f,
	0xe9, 0x28, 0x4f, 0x5a, 0xbf, 0x76, 0x94, 0xe8, 0xea, 0xe2, 0x04, 0x66, 0x1d, 0x8e, 0xb1, 0xd0,
	0xb7, 0x9f, 0x8a, 0xef, 0xf4, 0x14, 0x46, 0x0f, 0x32, 0xad, 0x90, 0x2c, 0x1a, 0x08, 0xbf, 0xa8,
	0x95, 0x55, 0xae, 0x5d, 0xb8, 0x3a, 0xf4, 0x4d, 0x6e, 0x6e, 0x4b, 0x87, 0x19, 0x39, 0x51, 0xbb,
	0x49, 0xab, 0xf8, 0x2b, 0x9c, 0x1c, 0x7a, 0xc1, 0x38, 0x8c, 0x95, 0x2e, 0x8b, 0x54, 0x6e, 0xc3,
	0xcf, 0x9a, 0xe5, 0x7e, 0x3c, 0xfa, 0x87, 0xf1, 0xd8, 0x00, 0xec, 0x2e, 0xc4, 0xa3, 0x8b, 0xdc,
	0xfb, 0xc3, 0x45, 0xfe, 0x04, 0xb3, 0x42, 0x5a, 0xa7, 0x13, 0x5d, 0xc8, 0xdc, 0x85, 0xf7, 0xe1,
	0xb4, 0x1d, 0xe9, 0xd5, 0x8e, 0x13, 0x5d, 0x61, 0x48, 0xfb, 0xa0, 0x49, 0x7b, 0xfc, 0x1d, 0xe6,
	0x5d, 0x71, 0x1d, 0xce, 0x0c, 0xb3, 0x35, 0xda, 0xc3, 0x70, 0x7e, 0x23, 0x54, 0x04, 0xb6, 0xce,
	0x92, 0x35, 0xa9, 0x6f, 0xa5, 0x93, 0x25, 0x61, 0x52, 0x14, 0xc4, 0xc4, 0x9f, 0x21, 0xf2, 0x7b,
	0xfe, 0xd9, 0x95, 0x57, 0x30, 0xa2, 0x67, 0xe7, 0xef, 0x77, 0x6b, 0x1d, 0xd1, 0xa3, 0xfa, 0xe1,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xf9, 0xa7, 0x6d, 0x7c, 0x05, 0x00, 0x00,
}
