// Code generated by protoc-gen-go. DO NOT EDIT.
// source: diagnosticReport.proto

package buffer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type DiagnosticReport struct {
	AssertedDate       string                 `protobuf:"bytes,1,opt,name=assertedDate" json:"assertedDate,omitempty"`
	Code               *Code                  `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Evidence           []*Evidence            `protobuf:"bytes,3,rep,name=evidence" json:"evidence,omitempty"`
	Text               *Text                  `protobuf:"bytes,4,opt,name=text" json:"text,omitempty"`
	OnsetDateTime      string                 `protobuf:"bytes,5,opt,name=onsetDateTime" json:"onsetDateTime,omitempty"`
	ClinicalStatus     string                 `protobuf:"bytes,6,opt,name=clinicalStatus" json:"clinicalStatus,omitempty"`
	Performer          []*DiagnosticPerformer `protobuf:"bytes,7,rep,name=performer" json:"performer,omitempty"`
	BodySite           []*BodySite            `protobuf:"bytes,8,rep,name=bodySite" json:"bodySite,omitempty"`
	Id                 string                 `protobuf:"bytes,9,opt,name=id" json:"id,omitempty"`
	Subject            *Subject               `protobuf:"bytes,10,opt,name=subject" json:"subject,omitempty"`
	Category           []*Category            `protobuf:"bytes,11,rep,name=category" json:"category,omitempty"`
	Severity           *Severity              `protobuf:"bytes,12,opt,name=severity" json:"severity,omitempty"`
	BasedOn            []*BasedOn             `protobuf:"bytes,13,rep,name=basedOn" json:"basedOn,omitempty"`
	Issued             string                 `protobuf:"bytes,14,opt,name=issued" json:"issued,omitempty"`
	EffectiveDateTime  string                 `protobuf:"bytes,15,opt,name=effectiveDateTime" json:"effectiveDateTime,omitempty"`
	Status             string                 `protobuf:"bytes,16,opt,name=status" json:"status,omitempty"`
	PresentedForm      []*PresentedForm       `protobuf:"bytes,17,rep,name=presentedForm" json:"presentedForm,omitempty"`
	Asserter           *Asserter              `protobuf:"bytes,18,opt,name=asserter" json:"asserter,omitempty"`
	Stage              *Stage                 `protobuf:"bytes,19,opt,name=stage" json:"stage,omitempty"`
	ResourceType       string                 `protobuf:"bytes,20,opt,name=resourceType" json:"resourceType,omitempty"`
	Context            *Context               `protobuf:"bytes,21,opt,name=context" json:"context,omitempty"`
	VerificationStatus string                 `protobuf:"bytes,22,opt,name=verificationStatus" json:"verificationStatus,omitempty"`
	Result             []*Result              `protobuf:"bytes,23,rep,name=result" json:"result,omitempty"`
	Meta               *Meta                  `protobuf:"bytes,24,opt,name=meta" json:"meta,omitempty"`
}

func (m *DiagnosticReport) Reset()                    { *m = DiagnosticReport{} }
func (m *DiagnosticReport) String() string            { return proto.CompactTextString(m) }
func (*DiagnosticReport) ProtoMessage()               {}
func (*DiagnosticReport) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *DiagnosticReport) GetAssertedDate() string {
	if m != nil {
		return m.AssertedDate
	}
	return ""
}

func (m *DiagnosticReport) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *DiagnosticReport) GetEvidence() []*Evidence {
	if m != nil {
		return m.Evidence
	}
	return nil
}

func (m *DiagnosticReport) GetText() *Text {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *DiagnosticReport) GetOnsetDateTime() string {
	if m != nil {
		return m.OnsetDateTime
	}
	return ""
}

func (m *DiagnosticReport) GetClinicalStatus() string {
	if m != nil {
		return m.ClinicalStatus
	}
	return ""
}

func (m *DiagnosticReport) GetPerformer() []*DiagnosticPerformer {
	if m != nil {
		return m.Performer
	}
	return nil
}

func (m *DiagnosticReport) GetBodySite() []*BodySite {
	if m != nil {
		return m.BodySite
	}
	return nil
}

func (m *DiagnosticReport) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DiagnosticReport) GetSubject() *Subject {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *DiagnosticReport) GetCategory() []*Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *DiagnosticReport) GetSeverity() *Severity {
	if m != nil {
		return m.Severity
	}
	return nil
}

func (m *DiagnosticReport) GetBasedOn() []*BasedOn {
	if m != nil {
		return m.BasedOn
	}
	return nil
}

func (m *DiagnosticReport) GetIssued() string {
	if m != nil {
		return m.Issued
	}
	return ""
}

func (m *DiagnosticReport) GetEffectiveDateTime() string {
	if m != nil {
		return m.EffectiveDateTime
	}
	return ""
}

func (m *DiagnosticReport) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *DiagnosticReport) GetPresentedForm() []*PresentedForm {
	if m != nil {
		return m.PresentedForm
	}
	return nil
}

func (m *DiagnosticReport) GetAsserter() *Asserter {
	if m != nil {
		return m.Asserter
	}
	return nil
}

func (m *DiagnosticReport) GetStage() *Stage {
	if m != nil {
		return m.Stage
	}
	return nil
}

func (m *DiagnosticReport) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *DiagnosticReport) GetContext() *Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *DiagnosticReport) GetVerificationStatus() string {
	if m != nil {
		return m.VerificationStatus
	}
	return ""
}

func (m *DiagnosticReport) GetResult() []*Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *DiagnosticReport) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Result struct {
	Reference string `protobuf:"bytes,1,opt,name=reference" json:"reference,omitempty"`
	Display   string `protobuf:"bytes,2,opt,name=display" json:"display,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *Result) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *Result) GetDisplay() string {
	if m != nil {
		return m.Display
	}
	return ""
}

type PresentedForm struct {
	Hash        string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	Language    string `protobuf:"bytes,2,opt,name=language" json:"language,omitempty"`
	Title       string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Creation    string `protobuf:"bytes,4,opt,name=creation" json:"creation,omitempty"`
	ContentType string `protobuf:"bytes,5,opt,name=contentType" json:"contentType,omitempty"`
	Data        string `protobuf:"bytes,6,opt,name=data" json:"data,omitempty"`
}

func (m *PresentedForm) Reset()                    { *m = PresentedForm{} }
func (m *PresentedForm) String() string            { return proto.CompactTextString(m) }
func (*PresentedForm) ProtoMessage()               {}
func (*PresentedForm) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *PresentedForm) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *PresentedForm) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *PresentedForm) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PresentedForm) GetCreation() string {
	if m != nil {
		return m.Creation
	}
	return ""
}

func (m *PresentedForm) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *PresentedForm) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type DiagnosticPerformer struct {
	Actor *Actor `protobuf:"bytes,1,opt,name=actor" json:"actor,omitempty"`
}

func (m *DiagnosticPerformer) Reset()                    { *m = DiagnosticPerformer{} }
func (m *DiagnosticPerformer) String() string            { return proto.CompactTextString(m) }
func (*DiagnosticPerformer) ProtoMessage()               {}
func (*DiagnosticPerformer) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *DiagnosticPerformer) GetActor() *Actor {
	if m != nil {
		return m.Actor
	}
	return nil
}

func init() {
	proto.RegisterType((*DiagnosticReport)(nil), "buffer.DiagnosticReport")
	proto.RegisterType((*Result)(nil), "buffer.Result")
	proto.RegisterType((*PresentedForm)(nil), "buffer.PresentedForm")
	proto.RegisterType((*DiagnosticPerformer)(nil), "buffer.DiagnosticPerformer")
}

func init() { proto.RegisterFile("diagnosticReport.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 638 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xcb, 0x6e, 0xdb, 0x3a,
	0x10, 0x85, 0xf3, 0xb0, 0x63, 0xfa, 0x91, 0x84, 0x79, 0x5c, 0x22, 0xf7, 0x2e, 0x0c, 0xdf, 0x22,
	0x48, 0x81, 0xc0, 0x8b, 0x74, 0xd5, 0x76, 0xd3, 0x3c, 0xda, 0x5d, 0xd1, 0x80, 0xce, 0x0f, 0xd0,
	0xe4, 0xc8, 0x61, 0x61, 0x8b, 0x06, 0x39, 0x0a, 0xe2, 0x2f, 0xea, 0x2f, 0xf5, 0x73, 0x0a, 0x0e,
	0x25, 0xc5, 0x4a, 0xb3, 0xd3, 0x9c, 0x73, 0x78, 0x38, 0x33, 0x9c, 0x11, 0x3b, 0x35, 0x56, 0xcd,
	0x73, 0x17, 0xd0, 0x6a, 0x09, 0x2b, 0xe7, 0x71, 0xb2, 0xf2, 0x0e, 0x1d, 0x6f, 0xcf, 0x8a, 0x2c,
	0x03, 0x7f, 0xd6, 0xd7, 0x6e, 0xb9, 0x74, 0x79, 0x42, 0xc7, 0xbf, 0x3b, 0xec, 0xe0, 0xee, 0xd5,
	0x01, 0x3e, 0x66, 0x7d, 0x15, 0x02, 0x78, 0x04, 0x73, 0xa7, 0x10, 0x44, 0x6b, 0xd4, 0xba, 0xe8,
	0xca, 0x06, 0xc6, 0x47, 0x6c, 0x47, 0x3b, 0x03, 0x62, 0x6b, 0xd4, 0xba, 0xe8, 0x5d, 0xf5, 0x27,
	0xc9, 0x7d, 0x72, 0xeb, 0x0c, 0x48, 0x62, 0xf8, 0x25, 0xdb, 0x83, 0x27, 0x6b, 0x20, 0xd7, 0x20,
	0xb6, 0x47, 0xdb, 0x17, 0xbd, 0xab, 0x83, 0x4a, 0xf5, 0xb5, 0xc4, 0x65, 0xad, 0x88, 0x7e, 0x08,
	0xcf, 0x28, 0x76, 0x9a, 0x7e, 0x0f, 0xf0, 0x8c, 0x92, 0x18, 0xfe, 0x8e, 0x0d, 0x5c, 0x1e, 0x00,
	0xe3, 0xf5, 0x0f, 0x76, 0x09, 0x62, 0x97, 0xd2, 0x6a, 0x82, 0xfc, 0x9c, 0x0d, 0xf5, 0xc2, 0xe6,
	0x56, 0xab, 0xc5, 0x14, 0x15, 0x16, 0x41, 0xb4, 0x49, 0xf6, 0x0a, 0xe5, 0x1f, 0x59, 0x77, 0x05,
	0x3e, 0x73, 0x7e, 0x09, 0x5e, 0x74, 0x28, 0xbd, 0x7f, 0xab, 0x4b, 0x5f, 0x1a, 0x72, 0x5f, 0x49,
	0xe4, 0x8b, 0x3a, 0x16, 0x36, 0x73, 0x66, 0x3d, 0xb5, 0x08, 0x62, 0xaf, 0x59, 0xd8, 0x4d, 0x89,
	0xcb, 0x5a, 0xc1, 0x87, 0x6c, 0xcb, 0x1a, 0xd1, 0xa5, 0x24, 0xb6, 0xac, 0xe1, 0xef, 0x59, 0x27,
	0x14, 0xb3, 0x9f, 0xa0, 0x51, 0x30, 0xaa, 0x75, 0xbf, 0x3a, 0x3c, 0x4d, 0xb0, 0xac, 0xf8, 0x78,
	0x91, 0x56, 0x08, 0x73, 0xe7, 0xd7, 0xa2, 0xd7, 0xbc, 0xe8, 0xb6, 0xc4, 0x65, 0xad, 0x88, 0xea,
	0x00, 0x4f, 0xe0, 0x2d, 0xae, 0x45, 0x9f, 0x9c, 0x6b, 0xf5, 0xb4, 0xc4, 0x65, 0xad, 0x88, 0x69,
	0xcc, 0x54, 0x00, 0xf3, 0x23, 0x17, 0x03, 0xb2, 0xae, 0xd3, 0xb8, 0x49, 0xb0, 0xac, 0x78, 0x7e,
	0xca, 0xda, 0x36, 0x84, 0x02, 0x8c, 0x18, 0x52, 0x15, 0x65, 0xc4, 0x2f, 0xd9, 0x21, 0x64, 0x19,
	0x68, 0xb4, 0x4f, 0x50, 0x3f, 0xca, 0x3e, 0x49, 0xfe, 0x26, 0xa2, 0x4b, 0x48, 0x0f, 0x72, 0x90,
	0x5c, 0x52, 0xc4, 0x3f, 0xb3, 0xc1, 0xca, 0x43, 0x80, 0x1c, 0xc1, 0x7c, 0x73, 0x7e, 0x29, 0x0e,
	0x29, 0x9d, 0x93, 0x2a, 0x9d, 0xfb, 0x4d, 0x52, 0x36, 0xb5, 0xb1, 0xe6, 0x72, 0x2a, 0xbd, 0xe0,
	0xcd, 0x9a, 0xaf, 0x4b, 0x5c, 0xd6, 0x0a, 0xfe, 0x3f, 0xdb, 0x0d, 0xa8, 0xe6, 0x20, 0x8e, 0x48,
	0x3a, 0xa8, 0xdb, 0x13, 0x41, 0x99, 0xb8, 0x38, 0xfc, 0x1e, 0x82, 0x2b, 0xbc, 0x86, 0x87, 0xf5,
	0x0a, 0xc4, 0x71, 0x1a, 0xfe, 0x4d, 0x2c, 0x36, 0x4f, 0xbb, 0x9c, 0xe6, 0xf5, 0xa4, 0xf9, 0x86,
	0xb7, 0x09, 0x96, 0x15, 0xcf, 0x27, 0x8c, 0xc7, 0x8e, 0x67, 0x56, 0x2b, 0xb4, 0x2e, 0x2f, 0x67,
	0xf2, 0x94, 0x4c, 0xdf, 0x60, 0xf8, 0x39, 0x6b, 0x7b, 0x08, 0xc5, 0x02, 0xc5, 0x3f, 0xd4, 0x87,
	0x61, 0xe5, 0x2c, 0x09, 0x95, 0x25, 0x1b, 0xf7, 0x65, 0x09, 0xa8, 0x84, 0x68, 0xee, 0xcb, 0x77,
	0x40, 0x25, 0x89, 0x19, 0x7f, 0x61, 0xed, 0x74, 0x86, 0xff, 0xc7, 0xba, 0x1e, 0x32, 0xf0, 0xb4,
	0x8a, 0x69, 0x99, 0x5f, 0x00, 0x2e, 0x58, 0xc7, 0xd8, 0xb0, 0x5a, 0xa8, 0x35, 0x2d, 0x73, 0x57,
	0x56, 0xe1, 0xf8, 0x57, 0x8b, 0x0d, 0x1a, 0xed, 0xe7, 0x9c, 0xed, 0x3c, 0xaa, 0xf0, 0x58, 0x9a,
	0xd0, 0x37, 0x3f, 0x63, 0x7b, 0x0b, 0x95, 0xcf, 0x8b, 0xd8, 0xd8, 0x64, 0x50, 0xc7, 0xfc, 0x98,
	0xed, 0xa2, 0xc5, 0x45, 0xfc, 0x01, 0x44, 0x22, 0x05, 0xf1, 0x84, 0xf6, 0x40, 0x55, 0xd3, 0xbe,
	0x77, 0x65, 0x1d, 0xf3, 0x11, 0xeb, 0x51, 0xeb, 0x72, 0xa4, 0xee, 0xa7, 0x1d, 0xdf, 0x84, 0x62,
	0x0e, 0x46, 0xa1, 0x2a, 0xf7, 0x9a, 0xbe, 0xc7, 0x9f, 0xd8, 0xd1, 0x1b, 0x4b, 0x1b, 0x1f, 0x5c,
	0x69, 0x74, 0x9e, 0xf2, 0xdd, 0x78, 0xf0, 0xeb, 0x08, 0xca, 0xc4, 0xcd, 0xda, 0xf4, 0x27, 0xfc,
	0xf0, 0x27, 0x00, 0x00, 0xff, 0xff, 0x68, 0x52, 0x16, 0x17, 0x39, 0x05, 0x00, 0x00,
}
