// Code generated by protoc-gen-go.
// source: diagnostic-report.proto
// DO NOT EDIT!

package buffer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Diagnosticreport struct {
	AssertedDate       string                 `protobuf:"bytes,1,opt,name=assertedDate" json:"assertedDate,omitempty"`
	Code               *Code                  `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Evidence           []*Evidence            `protobuf:"bytes,3,rep,name=evidence" json:"evidence,omitempty"`
	Text               *Text                  `protobuf:"bytes,4,opt,name=text" json:"text,omitempty"`
	OnsetDateTime      string                 `protobuf:"bytes,5,opt,name=onsetDateTime" json:"onsetDateTime,omitempty"`
	ClinicalStatus     string                 `protobuf:"bytes,6,opt,name=clinicalStatus" json:"clinicalStatus,omitempty"`
	Performer          []*DiagnosticPerformer `protobuf:"bytes,7,rep,name=performer" json:"performer,omitempty"`
	BodySite           []*BodySite            `protobuf:"bytes,8,rep,name=bodySite" json:"bodySite,omitempty"`
	Id                 string                 `protobuf:"bytes,9,opt,name=id" json:"id,omitempty"`
	Subject            *Subject               `protobuf:"bytes,10,opt,name=subject" json:"subject,omitempty"`
	Category           []*Category            `protobuf:"bytes,11,rep,name=category" json:"category,omitempty"`
	Severity           *Severity              `protobuf:"bytes,12,opt,name=severity" json:"severity,omitempty"`
	BasedOn            []*BasedOn             `protobuf:"bytes,13,rep,name=basedOn" json:"basedOn,omitempty"`
	Issued             string                 `protobuf:"bytes,14,opt,name=issued" json:"issued,omitempty"`
	EffectiveDateTime  string                 `protobuf:"bytes,15,opt,name=effectiveDateTime" json:"effectiveDateTime,omitempty"`
	Status             string                 `protobuf:"bytes,16,opt,name=status" json:"status,omitempty"`
	PresentedForm      []*PresentedForm       `protobuf:"bytes,17,rep,name=presentedForm" json:"presentedForm,omitempty"`
	Asserter           *Asserter              `protobuf:"bytes,18,opt,name=asserter" json:"asserter,omitempty"`
	Stage              *Stage                 `protobuf:"bytes,19,opt,name=stage" json:"stage,omitempty"`
	ResourceType       string                 `protobuf:"bytes,20,opt,name=resourceType" json:"resourceType,omitempty"`
	Context            *Context               `protobuf:"bytes,21,opt,name=context" json:"context,omitempty"`
	VerificationStatus string                 `protobuf:"bytes,22,opt,name=verificationStatus" json:"verificationStatus,omitempty"`
	Result             []*Result              `protobuf:"bytes,23,rep,name=result" json:"result,omitempty"`
}

func (m *Diagnosticreport) Reset()                    { *m = Diagnosticreport{} }
func (m *Diagnosticreport) String() string            { return proto.CompactTextString(m) }
func (*Diagnosticreport) ProtoMessage()               {}
func (*Diagnosticreport) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *Diagnosticreport) GetAssertedDate() string {
	if m != nil {
		return m.AssertedDate
	}
	return ""
}

func (m *Diagnosticreport) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *Diagnosticreport) GetEvidence() []*Evidence {
	if m != nil {
		return m.Evidence
	}
	return nil
}

func (m *Diagnosticreport) GetText() *Text {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *Diagnosticreport) GetOnsetDateTime() string {
	if m != nil {
		return m.OnsetDateTime
	}
	return ""
}

func (m *Diagnosticreport) GetClinicalStatus() string {
	if m != nil {
		return m.ClinicalStatus
	}
	return ""
}

func (m *Diagnosticreport) GetPerformer() []*DiagnosticPerformer {
	if m != nil {
		return m.Performer
	}
	return nil
}

func (m *Diagnosticreport) GetBodySite() []*BodySite {
	if m != nil {
		return m.BodySite
	}
	return nil
}

func (m *Diagnosticreport) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Diagnosticreport) GetSubject() *Subject {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *Diagnosticreport) GetCategory() []*Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *Diagnosticreport) GetSeverity() *Severity {
	if m != nil {
		return m.Severity
	}
	return nil
}

func (m *Diagnosticreport) GetBasedOn() []*BasedOn {
	if m != nil {
		return m.BasedOn
	}
	return nil
}

func (m *Diagnosticreport) GetIssued() string {
	if m != nil {
		return m.Issued
	}
	return ""
}

func (m *Diagnosticreport) GetEffectiveDateTime() string {
	if m != nil {
		return m.EffectiveDateTime
	}
	return ""
}

func (m *Diagnosticreport) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Diagnosticreport) GetPresentedForm() []*PresentedForm {
	if m != nil {
		return m.PresentedForm
	}
	return nil
}

func (m *Diagnosticreport) GetAsserter() *Asserter {
	if m != nil {
		return m.Asserter
	}
	return nil
}

func (m *Diagnosticreport) GetStage() *Stage {
	if m != nil {
		return m.Stage
	}
	return nil
}

func (m *Diagnosticreport) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *Diagnosticreport) GetContext() *Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *Diagnosticreport) GetVerificationStatus() string {
	if m != nil {
		return m.VerificationStatus
	}
	return ""
}

func (m *Diagnosticreport) GetResult() []*Result {
	if m != nil {
		return m.Result
	}
	return nil
}

type Result struct {
	Reference string `protobuf:"bytes,1,opt,name=reference" json:"reference,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *Result) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

type PresentedForm struct {
	Hash        string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
	Language    string `protobuf:"bytes,2,opt,name=language" json:"language,omitempty"`
	Title       string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Creation    string `protobuf:"bytes,4,opt,name=creation" json:"creation,omitempty"`
	ContentType string `protobuf:"bytes,5,opt,name=contentType" json:"contentType,omitempty"`
	Data        string `protobuf:"bytes,6,opt,name=data" json:"data,omitempty"`
}

func (m *PresentedForm) Reset()                    { *m = PresentedForm{} }
func (m *PresentedForm) String() string            { return proto.CompactTextString(m) }
func (*PresentedForm) ProtoMessage()               {}
func (*PresentedForm) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *PresentedForm) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *PresentedForm) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *PresentedForm) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PresentedForm) GetCreation() string {
	if m != nil {
		return m.Creation
	}
	return ""
}

func (m *PresentedForm) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *PresentedForm) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type DiagnosticPerformer struct {
	Actor *Actor `protobuf:"bytes,1,opt,name=actor" json:"actor,omitempty"`
}

func (m *DiagnosticPerformer) Reset()                    { *m = DiagnosticPerformer{} }
func (m *DiagnosticPerformer) String() string            { return proto.CompactTextString(m) }
func (*DiagnosticPerformer) ProtoMessage()               {}
func (*DiagnosticPerformer) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *DiagnosticPerformer) GetActor() *Actor {
	if m != nil {
		return m.Actor
	}
	return nil
}

func init() {
	proto.RegisterType((*Diagnosticreport)(nil), "buffer.Diagnosticreport")
	proto.RegisterType((*Result)(nil), "buffer.Result")
	proto.RegisterType((*PresentedForm)(nil), "buffer.PresentedForm")
	proto.RegisterType((*DiagnosticPerformer)(nil), "buffer.DiagnosticPerformer")
}

func init() { proto.RegisterFile("diagnostic-report.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 613 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0xdb, 0x4e, 0x1b, 0x3d,
	0x10, 0xc7, 0x95, 0x00, 0x81, 0x38, 0x07, 0xc0, 0x9c, 0x2c, 0xbe, 0xef, 0x22, 0x4a, 0x2b, 0x44,
	0x25, 0x9a, 0x0b, 0x7a, 0xd5, 0xf6, 0x8a, 0x43, 0x7b, 0x5b, 0xe4, 0xf0, 0x02, 0x8e, 0x77, 0x36,
	0xb8, 0x4a, 0xd6, 0x91, 0x3d, 0x8b, 0xc8, 0x13, 0xf5, 0x0d, 0xfa, 0x7c, 0x95, 0xc7, 0xbb, 0x26,
	0xdb, 0x72, 0xb7, 0xfe, 0xfd, 0xff, 0x1e, 0xcf, 0x8c, 0x3d, 0xcb, 0xce, 0x32, 0xa3, 0xe6, 0x85,
	0xf5, 0x68, 0xf4, 0x47, 0x07, 0x2b, 0xeb, 0x70, 0xb2, 0x72, 0x16, 0x2d, 0xef, 0xcc, 0xca, 0x3c,
	0x07, 0x77, 0xde, 0xd7, 0x76, 0xb9, 0xb4, 0x45, 0xa4, 0xe3, 0xdf, 0xbb, 0xec, 0xe0, 0x3e, 0xed,
	0x88, 0x1b, 0xf8, 0x98, 0xf5, 0x95, 0xf7, 0xe0, 0x10, 0xb2, 0x7b, 0x85, 0x20, 0x5a, 0xa3, 0xd6,
	0x65, 0x57, 0x36, 0x18, 0x1f, 0xb1, 0x6d, 0x6d, 0x33, 0x10, 0xed, 0x51, 0xeb, 0xb2, 0x77, 0xdd,
	0x9f, 0xc4, 0xe8, 0x93, 0x3b, 0x9b, 0x81, 0x24, 0x85, 0x5f, 0xb1, 0x3d, 0x78, 0x36, 0x19, 0x14,
	0x1a, 0xc4, 0xd6, 0x68, 0xeb, 0xb2, 0x77, 0x7d, 0x50, 0xbb, 0xbe, 0x55, 0x5c, 0x26, 0x47, 0x88,
	0x87, 0xf0, 0x82, 0x62, 0xbb, 0x19, 0xef, 0x11, 0x5e, 0x50, 0x92, 0xc2, 0xdf, 0xb3, 0x81, 0x2d,
	0x3c, 0x60, 0x38, 0xfe, 0xd1, 0x2c, 0x41, 0xec, 0x50, 0x5a, 0x4d, 0xc8, 0x2f, 0xd8, 0x50, 0x2f,
	0x4c, 0x61, 0xb4, 0x5a, 0x4c, 0x51, 0x61, 0xe9, 0x45, 0x87, 0x6c, 0x7f, 0x51, 0xfe, 0x99, 0x75,
	0x57, 0xe0, 0x72, 0xeb, 0x96, 0xe0, 0xc4, 0x2e, 0xa5, 0xf7, 0x5f, 0x7d, 0xe8, 0x6b, 0x43, 0x1e,
	0x6a, 0x8b, 0x7c, 0x75, 0x87, 0xc2, 0x66, 0x36, 0x5b, 0x4f, 0x0d, 0x82, 0xd8, 0x6b, 0x16, 0x76,
	0x5b, 0x71, 0x99, 0x1c, 0x7c, 0xc8, 0xda, 0x26, 0x13, 0x5d, 0x4a, 0xa2, 0x6d, 0x32, 0xfe, 0x81,
	0xed, 0xfa, 0x72, 0xf6, 0x13, 0x34, 0x0a, 0x46, 0xb5, 0xee, 0xd7, 0x9b, 0xa7, 0x11, 0xcb, 0x5a,
	0x0f, 0x07, 0x69, 0x85, 0x30, 0xb7, 0x6e, 0x2d, 0x7a, 0xcd, 0x83, 0xee, 0x2a, 0x2e, 0x93, 0x23,
	0xb8, 0x3d, 0x3c, 0x83, 0x33, 0xb8, 0x16, 0x7d, 0x8a, 0x9c, 0xdc, 0xd3, 0x8a, 0xcb, 0xe4, 0x08,
	0x69, 0xcc, 0x94, 0x87, 0xec, 0x47, 0x21, 0x06, 0x14, 0x3a, 0xa5, 0x71, 0x1b, 0xb1, 0xac, 0x75,
	0x7e, 0xca, 0x3a, 0xc6, 0xfb, 0x12, 0x32, 0x31, 0xa4, 0x2a, 0xaa, 0x15, 0xbf, 0x62, 0x87, 0x90,
	0xe7, 0xa0, 0xd1, 0x3c, 0x43, 0xba, 0x94, 0x7d, 0xb2, 0xfc, 0x2b, 0x84, 0x28, 0x3e, 0x5e, 0xc8,
	0x41, 0x8c, 0x12, 0x57, 0xfc, 0x2b, 0x1b, 0xac, 0x1c, 0x78, 0x28, 0x10, 0xb2, 0xef, 0xd6, 0x2d,
	0xc5, 0x21, 0xa5, 0x73, 0x52, 0xa7, 0xf3, 0xb0, 0x29, 0xca, 0xa6, 0x37, 0xd4, 0x5c, 0xbd, 0x4a,
	0x27, 0x78, 0xb3, 0xe6, 0x9b, 0x8a, 0xcb, 0xe4, 0xe0, 0xef, 0xd8, 0x8e, 0x47, 0x35, 0x07, 0x71,
	0x44, 0xd6, 0x41, 0x6a, 0x4f, 0x80, 0x32, 0x6a, 0xe1, 0xf1, 0x3b, 0xf0, 0xb6, 0x74, 0x1a, 0x1e,
	0xd7, 0x2b, 0x10, 0xc7, 0xf1, 0xf1, 0x6f, 0xb2, 0xd0, 0x3c, 0x6d, 0x0b, 0x7a, 0xaf, 0x27, 0xcd,
	0x3b, 0xbc, 0x8b, 0x58, 0xd6, 0x3a, 0x9f, 0x30, 0x1e, 0x3a, 0x9e, 0x1b, 0xad, 0xd0, 0xd8, 0xa2,
	0x7a, 0x93, 0xa7, 0x14, 0xf4, 0x0d, 0x85, 0x5f, 0xb0, 0x8e, 0x03, 0x5f, 0x2e, 0x50, 0x9c, 0x51,
	0x1f, 0x86, 0x75, 0x64, 0x49, 0x54, 0x56, 0xea, 0xf8, 0x82, 0x75, 0x22, 0xe1, 0xff, 0xb3, 0xae,
	0x83, 0x1c, 0x1c, 0x0d, 0x5a, 0x1c, 0xd5, 0x57, 0x30, 0xfe, 0xd5, 0x62, 0x83, 0x46, 0x0b, 0x39,
	0x67, 0xdb, 0x4f, 0xca, 0x3f, 0x55, 0x56, 0xfa, 0xe6, 0xe7, 0x6c, 0x6f, 0xa1, 0x8a, 0x79, 0x19,
	0x9a, 0xd3, 0x26, 0x9e, 0xd6, 0xfc, 0x98, 0xed, 0xa0, 0xc1, 0x45, 0x18, 0xe2, 0x20, 0xc4, 0x45,
	0xd8, 0xa1, 0x1d, 0x50, 0xe6, 0x34, 0xb3, 0x5d, 0x99, 0xd6, 0x7c, 0xc4, 0x7a, 0x54, 0x7e, 0x81,
	0xd4, 0xc1, 0x38, 0xa7, 0x9b, 0x28, 0xe4, 0x90, 0x29, 0x54, 0xd5, 0x6c, 0xd2, 0xf7, 0xf8, 0x0b,
	0x3b, 0x7a, 0x63, 0xf0, 0xc2, 0xa5, 0x29, 0x8d, 0xd6, 0x51, 0xbe, 0x1b, 0x97, 0x76, 0x13, 0xa0,
	0x8c, 0xda, 0xac, 0x43, 0x7f, 0xb3, 0x4f, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xca, 0x9a, 0x6b,
	0x92, 0xfe, 0x04, 0x00, 0x00,
}
