// Code generated by protoc-gen-go. DO NOT EDIT.
// source: procedure.proto

package buffer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Procedure struct {
	Status          string           `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	PerformedPeriod *PerformedPeriod `protobuf:"bytes,2,opt,name=performedPeriod" json:"performedPeriod,omitempty"`
	Code            *Code            `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
	ResourceType    string           `protobuf:"bytes,4,opt,name=resourceType" json:"resourceType,omitempty"`
	Text            *Text            `protobuf:"bytes,5,opt,name=text" json:"text,omitempty"`
	FollowUp        []*FollowUp      `protobuf:"bytes,6,rep,name=followUp" json:"followUp,omitempty"`
	Performer       []*PPerformer    `protobuf:"bytes,7,rep,name=performer" json:"performer,omitempty"`
	BodySite        []*BodySite      `protobuf:"bytes,8,rep,name=bodySite" json:"bodySite,omitempty"`
	Context         *Context         `protobuf:"bytes,9,opt,name=context" json:"context,omitempty"`
	Report          []*Report        `protobuf:"bytes,10,rep,name=report" json:"report,omitempty"`
	ReasonCode      []*ReasonCode    `protobuf:"bytes,11,rep,name=reasonCode" json:"reasonCode,omitempty"`
	Outcome         *Outcome         `protobuf:"bytes,12,opt,name=outcome" json:"outcome,omitempty"`
	Id              string           `protobuf:"bytes,13,opt,name=id" json:"id,omitempty"`
	Subject         *Subject         `protobuf:"bytes,14,opt,name=subject" json:"subject,omitempty"`
}

func (m *Procedure) Reset()                    { *m = Procedure{} }
func (m *Procedure) String() string            { return proto.CompactTextString(m) }
func (*Procedure) ProtoMessage()               {}
func (*Procedure) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{0} }

func (m *Procedure) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Procedure) GetPerformedPeriod() *PerformedPeriod {
	if m != nil {
		return m.PerformedPeriod
	}
	return nil
}

func (m *Procedure) GetCode() *Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *Procedure) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *Procedure) GetText() *Text {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *Procedure) GetFollowUp() []*FollowUp {
	if m != nil {
		return m.FollowUp
	}
	return nil
}

func (m *Procedure) GetPerformer() []*PPerformer {
	if m != nil {
		return m.Performer
	}
	return nil
}

func (m *Procedure) GetBodySite() []*BodySite {
	if m != nil {
		return m.BodySite
	}
	return nil
}

func (m *Procedure) GetContext() *Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *Procedure) GetReport() []*Report {
	if m != nil {
		return m.Report
	}
	return nil
}

func (m *Procedure) GetReasonCode() []*ReasonCode {
	if m != nil {
		return m.ReasonCode
	}
	return nil
}

func (m *Procedure) GetOutcome() *Outcome {
	if m != nil {
		return m.Outcome
	}
	return nil
}

func (m *Procedure) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Procedure) GetSubject() *Subject {
	if m != nil {
		return m.Subject
	}
	return nil
}

type Outcome struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *Outcome) Reset()                    { *m = Outcome{} }
func (m *Outcome) String() string            { return proto.CompactTextString(m) }
func (*Outcome) ProtoMessage()               {}
func (*Outcome) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{1} }

func (m *Outcome) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type ReasonCode struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *ReasonCode) Reset()                    { *m = ReasonCode{} }
func (m *ReasonCode) String() string            { return proto.CompactTextString(m) }
func (*ReasonCode) ProtoMessage()               {}
func (*ReasonCode) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{2} }

func (m *ReasonCode) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Report struct {
	Display   string `protobuf:"bytes,1,opt,name=display" json:"display,omitempty"`
	Reference string `protobuf:"bytes,2,opt,name=reference" json:"reference,omitempty"`
}

func (m *Report) Reset()                    { *m = Report{} }
func (m *Report) String() string            { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()               {}
func (*Report) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{3} }

func (m *Report) GetDisplay() string {
	if m != nil {
		return m.Display
	}
	return ""
}

func (m *Report) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

type PPerformer struct {
	Role  *Role  `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
	Actor *Actor `protobuf:"bytes,2,opt,name=actor" json:"actor,omitempty"`
}

func (m *PPerformer) Reset()                    { *m = PPerformer{} }
func (m *PPerformer) String() string            { return proto.CompactTextString(m) }
func (*PPerformer) ProtoMessage()               {}
func (*PPerformer) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{4} }

func (m *PPerformer) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *PPerformer) GetActor() *Actor {
	if m != nil {
		return m.Actor
	}
	return nil
}

type FollowUp struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *FollowUp) Reset()                    { *m = FollowUp{} }
func (m *FollowUp) String() string            { return proto.CompactTextString(m) }
func (*FollowUp) ProtoMessage()               {}
func (*FollowUp) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{5} }

func (m *FollowUp) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type PerformedPeriod struct {
	Start string `protobuf:"bytes,1,opt,name=start" json:"start,omitempty"`
	End   string `protobuf:"bytes,2,opt,name=end" json:"end,omitempty"`
}

func (m *PerformedPeriod) Reset()                    { *m = PerformedPeriod{} }
func (m *PerformedPeriod) String() string            { return proto.CompactTextString(m) }
func (*PerformedPeriod) ProtoMessage()               {}
func (*PerformedPeriod) Descriptor() ([]byte, []int) { return fileDescriptor15, []int{6} }

func (m *PerformedPeriod) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *PerformedPeriod) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

func init() {
	proto.RegisterType((*Procedure)(nil), "buffer.Procedure")
	proto.RegisterType((*Outcome)(nil), "buffer.Outcome")
	proto.RegisterType((*ReasonCode)(nil), "buffer.ReasonCode")
	proto.RegisterType((*Report)(nil), "buffer.Report")
	proto.RegisterType((*PPerformer)(nil), "buffer.PPerformer")
	proto.RegisterType((*FollowUp)(nil), "buffer.FollowUp")
	proto.RegisterType((*PerformedPeriod)(nil), "buffer.PerformedPeriod")
}

func init() { proto.RegisterFile("procedure.proto", fileDescriptor15) }

var fileDescriptor15 = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0xa5, 0x5f, 0x69, 0x73, 0xdb, 0x6d, 0x97, 0x8b, 0xe8, 0x20, 0x2a, 0x25, 0x82, 0x54, 0x90,
	0x22, 0xf5, 0xc9, 0x37, 0x57, 0xc1, 0x57, 0xcb, 0x74, 0xfd, 0x01, 0x6d, 0xe6, 0x06, 0x22, 0x69,
	0x6e, 0xb8, 0x99, 0xe0, 0xf6, 0x27, 0xfa, 0xaf, 0x24, 0x93, 0x4c, 0xb3, 0x59, 0xf6, 0x2d, 0x73,
	0xce, 0xb9, 0x87, 0x73, 0x67, 0x4e, 0x60, 0x55, 0x08, 0xc7, 0x64, 0x2a, 0xa1, 0x6d, 0x21, 0x6c,
	0x19, 0x83, 0x53, 0x95, 0x24, 0x24, 0xaf, 0x17, 0x31, 0x9f, 0xcf, 0x9c, 0x37, 0x68, 0xf4, 0x6f,
	0x0c, 0xe1, 0xde, 0x2b, 0xf1, 0x25, 0x04, 0xa5, 0x3d, 0xda, 0xaa, 0x54, 0x83, 0xf5, 0x60, 0x13,
	0xea, 0xf6, 0x84, 0x77, 0xb0, 0x2a, 0x48, 0x12, 0x96, 0x33, 0x99, 0x3d, 0x49, 0xca, 0x46, 0x0d,
	0xd7, 0x83, 0xcd, 0x7c, 0xf7, 0x6a, 0xdb, 0xb8, 0x6e, 0xf7, 0x7d, 0x5a, 0x3f, 0xd5, 0xe3, 0x1a,
	0xc6, 0x31, 0x1b, 0x52, 0x23, 0x37, 0xb7, 0xf0, 0x73, 0x3f, 0xd8, 0x90, 0x76, 0x0c, 0x46, 0xb0,
	0x10, 0x2a, 0xb9, 0x92, 0x98, 0xee, 0x2f, 0x05, 0xa9, 0xb1, 0x8b, 0xd0, 0xc3, 0x6a, 0x17, 0x4b,
	0x0f, 0x56, 0x4d, 0xfa, 0x2e, 0xf7, 0xf4, 0x60, 0xb5, 0x63, 0xf0, 0x13, 0xcc, 0x12, 0xce, 0x32,
	0xfe, 0xfb, 0xbb, 0x50, 0xc1, 0x7a, 0xb4, 0x99, 0xef, 0x6e, 0xbd, 0xea, 0x67, 0x8b, 0xeb, 0xab,
	0x02, 0x3f, 0x43, 0xe8, 0x83, 0x8a, 0x9a, 0x3a, 0x39, 0x5e, 0x57, 0xf2, 0x3b, 0x89, 0xee, 0x44,
	0xb5, 0xff, 0x89, 0xcd, 0xe5, 0x90, 0x5a, 0x52, 0xb3, 0xbe, 0xff, 0xf7, 0x16, 0xd7, 0x57, 0x05,
	0x7e, 0x84, 0x69, 0xcc, 0xb9, 0x8b, 0x1c, 0xba, 0xc8, 0xab, 0x6e, 0x71, 0x07, 0x6b, 0xcf, 0xe3,
	0x07, 0x08, 0x84, 0x0a, 0x16, 0xab, 0xc0, 0xd9, 0x2e, 0xbd, 0x52, 0x3b, 0x54, 0xb7, 0x2c, 0xee,
	0x00, 0x84, 0x8e, 0x25, 0xe7, 0xf5, 0xd5, 0xa9, 0x79, 0x3f, 0xb3, 0xbe, 0x32, 0xfa, 0x91, 0xaa,
	0x8e, 0xc1, 0x95, 0x8d, 0xf9, 0x4c, 0x6a, 0xd1, 0x8f, 0xf1, 0xab, 0x81, 0xb5, 0xe7, 0x71, 0x09,
	0xc3, 0xd4, 0xa8, 0x1b, 0x77, 0xf7, 0xc3, 0xd4, 0xd4, 0xa3, 0x65, 0x75, 0xfa, 0x43, 0xb1, 0x55,
	0xcb, 0xfe, 0xe8, 0xa1, 0x81, 0xb5, 0xe7, 0xa3, 0xb7, 0x30, 0x6d, 0xed, 0x10, 0xdb, 0x77, 0x6a,
	0x6a, 0xe4, 0xbe, 0xa3, 0x35, 0x40, 0x17, 0xef, 0x59, 0xc5, 0x37, 0x08, 0x9a, 0x65, 0x51, 0xc1,
	0xd4, 0xa4, 0x65, 0x91, 0x1d, 0x2f, 0xad, 0xc0, 0x1f, 0xf1, 0x0d, 0x84, 0x42, 0x09, 0x09, 0xe5,
	0x31, 0xb9, 0x12, 0x86, 0xba, 0x03, 0xa2, 0x03, 0x40, 0xf7, 0x6c, 0x75, 0x5b, 0x84, 0x33, 0x72,
	0x16, 0x8f, 0xda, 0xa2, 0x39, 0x23, 0xed, 0x18, 0x7c, 0x0f, 0x93, 0x63, 0x6c, 0x59, 0xda, 0x3a,
	0xdf, 0x78, 0xc9, 0x5d, 0x0d, 0xea, 0x86, 0x8b, 0xde, 0xc1, 0xcc, 0x57, 0xe7, 0xd9, 0xd8, 0x5f,
	0x61, 0xf5, 0xa4, 0xfe, 0xf8, 0x02, 0x26, 0xa5, 0x3d, 0x8a, 0xd7, 0x35, 0x07, 0xbc, 0x85, 0x11,
	0xe5, 0xa6, 0x4d, 0x5d, 0x7f, 0x9e, 0x02, 0xf7, 0x17, 0x7e, 0xf9, 0x1f, 0x00, 0x00, 0xff, 0xff,
	0x69, 0xaf, 0x40, 0xa2, 0xae, 0x03, 0x00, 0x00,
}
